---
- hosts: '{{ host }}'
  remote_user: root
  gather_facts: false
  vars:
        app_name: '{{ app_name }}'
  tasks:
#####停止原来的服务
    - name: stop {{ app_name }} service
      shell: "sh /data/server/{{ app_name }}/stop.sh"
      register: result1
          
    - name: start {{ app_name }} app message
      debug: msg="{{ result1.stdout }}"
            
#####启动服务
    - name: start {{ app_name }} service
      shell: cd /data/server/{{ app_name }} && sh /data/server/{{ app_name }}/start.sh
      register: result2
        
    - name: start {{ app_name }} app message
      debug: msg="{{ result2.stdout }}"